"""
Cloud AI Outage Alert Script

Checks status of 5 AI cloud providers (OpenAI, Anthropic, AWS Bedrock,
Azure AI, GCP Vertex AI) and sends an email alert if any have active incidents.

Run: python src/notifications/alerts.py
Scheduled via: .github/workflows/outage-monitor.yml
"""

import sys
import os

# Path setup — allow imports from src/
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from dotenv import load_dotenv
load_dotenv(os.path.join(os.path.dirname(__file__), "..", "..", ".env"))

from providers.status import fetch_all_statuses, ServiceHealth
from notifications.email_sender import send_html_email


def build_outage_email_html(statuses):
    """Build an HTML email summarizing provider statuses."""
    status_colors = {
        ServiceHealth.OPERATIONAL: "#28a745",
        ServiceHealth.DEGRADED: "#fd7e14",
        ServiceHealth.PARTIAL_OUTAGE: "#dc3545",
        ServiceHealth.MAJOR_OUTAGE: "#dc3545",
        ServiceHealth.UNKNOWN: "#6c757d",
    }

    rows_html = ""
    for s in statuses:
        color = status_colors.get(s.status, "#6c757d")
        status_label = s.status.value.replace("_", " ").title()

        incidents_html = ""
        if s.incidents:
            items = "".join(
                f"<li>{inc['title']}</li>" for inc in s.incidents[:5]
            )
            incidents_html = f"<ul style='margin:4px 0;padding-left:20px;'>{items}</ul>"

        rows_html += f"""
        <tr>
            <td style="padding: 8px; border: 1px solid #ddd;">
                <span style="display:inline-block; width:12px; height:12px;
                      background:{color}; border-radius:50%; margin-right:6px;"></span>
                <strong>{s.provider}</strong>
            </td>
            <td style="padding: 8px; border: 1px solid #ddd; color:{color};">
                {status_label}
            </td>
            <td style="padding: 8px; border: 1px solid #ddd;">
                {s.description}{incidents_html}
            </td>
            <td style="padding: 8px; border: 1px solid #ddd;">
                <a href="{s.status_page_url}">Status Page</a>
            </td>
        </tr>
        """

    html = f"""
    <html>
    <body style="font-family: Arial, sans-serif; color: #333;">
        <h2>Cloud AI Service Outage Alert</h2>
        <p>One or more AI cloud providers are experiencing issues:</p>

        <table style="border-collapse: collapse; width: 100%; margin-top: 16px;">
            <thead>
                <tr style="background: #f8f9fa;">
                    <th style="padding: 8px; border: 1px solid #ddd; text-align: left;">Provider</th>
                    <th style="padding: 8px; border: 1px solid #ddd; text-align: left;">Status</th>
                    <th style="padding: 8px; border: 1px solid #ddd; text-align: left;">Details</th>
                    <th style="padding: 8px; border: 1px solid #ddd; text-align: left;">Link</th>
                </tr>
            </thead>
            <tbody>
                {rows_html}
            </tbody>
        </table>

        <p style="margin-top: 16px; color: #666; font-size: 12px;">
            Generated by Model Intelligence Dashboard
        </p>
    </body>
    </html>
    """
    return html


def main():
    print("Checking service status for 5 AI cloud providers...")
    statuses = fetch_all_statuses()

    for s in statuses:
        status_label = s.status.value.replace("_", " ").title()
        print(f"  {s.provider}: {status_label} — {s.description}")
        if s.error:
            print(f"    (Error: {s.error})")

    # Filter to non-operational providers
    issues = [s for s in statuses if s.status != ServiceHealth.OPERATIONAL]

    if not issues:
        print("\nAll 5 providers operational. No alert needed.")
        return

    provider_names = ", ".join(s.provider for s in issues)
    print(f"\nIssues detected: {provider_names}")

    subject = f"[Outage Alert] Issues detected: {provider_names}"
    html_body = build_outage_email_html(statuses)
    send_html_email(subject, html_body)


if __name__ == "__main__":
    main()
